{% set name = "zenoh-plugin-webserver" %}
{% set version = "1.3.4" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  - url: https://github.com/eclipse-zenoh/zenoh-plugin-webserver/archive/refs/tags/{{ version }}.tar.gz
    sha256: 60f327433eeeda27db20d43fcd6ff2178a7cb83ad3f522d573cf43d4c827a583

build:
  number: 0

# We use a multi-output recipe even if this recipe is single output as otherwise (at least in June 2024)
# the {{ version }}.{{ rust_compiler_version }} expression did not render correctly
outputs:
  - name: {{ name }}
    script: build_plugin.sh  # [unix]
    script: bld_plugin.bat  # [win]
    requirements:
      build:
        - {{ compiler('rust') }}
        - {{ stdlib('c') }}
        - cargo-bundle-licenses
        # required as on Linux unwind's rust functionality depends on gcc_s library
        - {{ compiler('c') }}
      host:
        - zenoh-rust-abi {{ version }}.{{ rust_compiler_version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libzenoh_plugin_webserver${SHLIB_EXT}  # [unix]
        - if not exist %PREFIX%\\Library\\bin\\zenoh_plugin_webserver.dll exit 1  # [win]

about:
  home: https://github.com/eclipse-zenoh/zenoh-plugin-webserver
  license: Apache-2.0 OR EPL-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A zenoh plug-in implementing an HTTP server mapping URLs to zenoh paths. This plugin can be used to set-up a Web server where the resources are retrieved from geo-distributed zenoh storages, each leveraging various backends (file system, database, memory...).

extra:
  recipe-maintainers:
    - traversaro
