{% set name = "zenoh-plugin-webserver" %}
{% set version = "0.11.0" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  - url: https://github.com/eclipse-zenoh/zenoh-plugin-webserver/archive/refs/tags/{{ version }}.tar.gz
    sha256: 483cee2c6c15189219d663ff1353621b91941c10730e2381b724a3509b2917c5

build:
  number: 0

outputs:
  # This is just a meta packages used to capture the exact version of zenoh (to which a unique Cargo.lock
  # used for all dependencies is associated) and the rust compiler version used, to capture the exacti ABI
  # of the zenoh plugins, and ensure that at runtime incompatible zenohd and plugins are never installed.
  - name: {{ name }}
    script: build_plugin.sh  # [unix]
    script: bld_plugin.bat  # [win]
    requirements:
      build:
        - {{ compiler('rust') }}
        - {{ stdlib('c') }}
        # required as on Linux unwind's rust functionality depends on gcc_s library
        - {{ compiler('c') }}
      host:
        - zenoh-rust-abi {{ version }}.{{ rust_compiler_version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libzenoh_plugin_webserver${SHLIB_EXT}  # [unix]
        - if not exist %PREFIX%\\Library\\bin\\zenoh_plugin_webserver.dll exit 1  # [win]

about:
  home: https://github.com/eclipse-zenoh/zenoh-plugin-webserver
  license: Apache-2.0 OR EPL-2.0
  license_file: 
    - LICENSE
    - THIRDPARTY.yml
  summary:  A zenoh plug-in implementing an HTTP server mapping URLs to zenoh paths. This plugin can be used to set-up a Web server where the resources are retrieved from geo-distributed zenoh storages, each leveraging various backends (file system, database, memory...).

extra:
  recipe-maintainers:
    - traversaro
